### ISSUE TITLE
ルーレット結果画面がすぐ消える

### ISSUE THREAD

**Issue by adeonhy** [PeachGangClub/peachgang.club#4]
スクショとれないだろ！！！！！！

**Comment by anoChick** [comment]
- a. 結果でたあとにタップしたら終了にする
- b. 結果でたあと、「もう一度回す」「やめる」ボタンを表示する

**Comment by adeonhy** [comment]
b

**Comment by anoChick** [comment]
bだといっぱい回せてたのしいけど、画面ゴチャつくので悩み。bつくってみるかも。37bitが。

**Comment by adeonhy** [comment]
twitter シェアボタンも付けるんだよあくしろよ

**Comment by anoChick** [comment]
やった
