### ISSUE TITLE
画面をSNSにシェアするボタン

### ISSUE THREAD

**Issue by anoChick** [PeachGangClub/peachgang.club#5]
https://github.com/PeachGangClub/peachgang.club/issues/4#issuecomment-782576454

OAuth認証なしで？？？？

**Comment by adeonhy** [comment]
ｵｰｯｽは梨で
```
http://twitter.com/share?url=[シェアするURL]&text=[ツイート内テキスト]&via=[ツイート内に含むユーザ名]&related=[ツイート後に表示されるユーザー]&hashtags=[ハッシュタグ]
```

**Comment by anoChick** [comment]
https://github.com/PeachGangClub/peachgang.club/pull/7
こういうことなのでcloseします
